#!usr/bin/env python3

import socket
import configuration
import queue
import threading

def receive (argc):
#Function responsible for listening to one client
    while True:
        c = argc(0)
        length = c.recv(1) #aquiring message length       
        msg = c.recv(length) #aquiring message itself
        
        while (len(msg) < length):
            msg+= c.recv
        
        message = (c , msg)
        msgQueue.put(message) #Add msg to queue 


#Configuring initial parametres
msgQueue = queue.Queue()

s = socket.socket() #Creating new socket
port, name = 12345, "nimi"    # configuration.configurator()
host = socket.gethostname() #
s.bind((host, port)) #Binding host to port

clients = [] #Creating a list containing client's addresses
threads = [] #Creating a list containing threads 

s.listen(5)
while True:

    c, addr =  s.accept()  #Accepting new connection 
   
    clients.append(c)  
   
    print("New connection from ", addr, "Type", type(c) )
    message = "Welcome to "+name
    msg = message.encode() 
    
    c.send(msg)
    argc = {c}    
    t = threading.Thread(target=receive,args=(argc))
    daemon = True #Set this thread to daemon thread
    threads.append(t)
    t.start()
    
    if msgQueue.qsize() > 0:

        for i in range(msgQueue.qsize()):

            client, msg = msgQueue.get() 

            for c in clients:
                if (c != client):
                    c.send(msg)
                else:
                    continue
            msgQueue.task_done()
                
